In [20]:
import pandas as pd
from datetime import datetime, timedelta

In [44]:
sleep_logs = pd.read_csv('data/sleep_list.csv')
sleep_logs = sleep_logs.drop_duplicates(subset='dateOfSleep', keep='last')
sleep_logs = sleep_logs.set_index('dateOfSleep').drop('Unnamed: 0', 1)
sleep_logs.head()

,awakeCount,awakeDuration,awakeningsCount,duration,efficiency,isMainSleep,logId,minutesAfterWakeup,minutesAsleep,minutesAwake,minutesToFallAsleep,restlessCount,restlessDuration,startTime,timeInBed
dateOfSleep,,,,,,,,,,,,,,,
2016-12-11,1,2,4,29640000,99,True,13198145736,0,489,5,0,3,3,2016-12-10T22:35:30.000,494
2016-12-10,0,0,8,26040000,95,True,13190828758,0,413,21,0,8,21,2016-12-09T23:59:00.000,434
2016-12-09,0,0,7,23640000,98,True,13187958640,0,385,9,0,7,9,2016-12-08T23:50:30.000,394
2016-12-08,1,1,8,25260000,97,True,13178275354,0,407,14,0,7,13,2016-12-07T23:10:00.000,421
2016-12-07,0,0,5,30360000,98,True,13169494070,0,496,10,0,5,10,2016-12-06T22:08:00.000,506

In [40]:
import traceback
date_iter = datetime.now().date()
end_date = pd.to_datetime('1/1/2016').date()
while date_iter > end_date:
    try:
        a = sleep_logs.loc[str(date_iter)]
    except:
        # traceback.print_exc()
        print(str(date_iter))
    date_iter -= timedelta(days=1)

2016-12-12
2016-09-02
2016-09-01
2016-08-31
2016-08-30
2016-08-29
2016-08-28
2016-08-27
2016-08-26
2016-08-25
2016-08-24
2016-08-10
2016-06-30

FitBit has no data from 8/24/2016 through 9/2/2016

FitBit has no data for 6/30/2016

In [16]:
type(sleep_logs.index.values[0])

str

In [34]:
end_date = pd.to_datetime('9/1/2016').date()
b = str(end_date)
a = sleep_logs.loc(str(end_date))
b

'2016-09-01'

In [36]:
a = sleep_logs.l('2016-09-01')
a.head()

AttributeError: '_LocIndexer' object has no attribute 'head'

In [38]:
sleep_logs.loc['2016-12-11']

awakeCount                                   1
awakeDuration                                2
awakeningsCount                              4
duration                              29640000
efficiency                                  99
isMainSleep                               True
logId                              13198145736
minutesAfterWakeup                           0
minutesAsleep                              489
minutesAwake                                 5
minutesToFallAsleep                          0
restlessCount                                3
restlessDuration                             3
startTime              2016-12-10T22:35:30.000
timeInBed                                  494
Name: 2016-12-11, dtype: object

In [49]:
sleep_logs = sleep_logs.sort_index(ascending=False)
sleep_logs.head()

,awakeCount,awakeDuration,awakeningsCount,duration,efficiency,isMainSleep,logId,minutesAfterWakeup,minutesAsleep,minutesAwake,minutesToFallAsleep,restlessCount,restlessDuration,startTime,timeInBed
dateOfSleep,,,,,,,,,,,,,,,
2016-12-11,1,2,4,29640000,99,True,13198145736,0,489,5,0,3,3,2016-12-10T22:35:30.000,494
2016-12-10,0,0,8,26040000,95,True,13190828758,0,413,21,0,8,21,2016-12-09T23:59:00.000,434
2016-12-09,0,0,7,23640000,98,True,13187958640,0,385,9,0,7,9,2016-12-08T23:50:30.000,394
2016-12-08,1,1,8,25260000,97,True,13178275354,0,407,14,0,7,13,2016-12-07T23:10:00.000,421
2016-12-07,0,0,5,30360000,98,True,13169494070,0,496,10,0,5,10,2016-12-06T22:08:00.000,506

In [50]:
sleep_logs.tail()

,awakeCount,awakeDuration,awakeningsCount,duration,efficiency,isMainSleep,logId,minutesAfterWakeup,minutesAsleep,minutesAwake,minutesToFallAsleep,restlessCount,restlessDuration,startTime,timeInBed
dateOfSleep,,,,,,,,,,,,,,,
2015-12-16,1,4,11,29640000,96,True,10355428583,0,472,22,0,10,18,2015-12-15T21:42:30.000,494
2015-12-15,3,9,10,22860000,93,True,10346392740,0,354,27,0,7,18,2015-12-14T23:48:00.000,381
2015-12-14,1,1,8,31440000,98,True,10338871982,0,512,12,0,7,11,2015-12-13T21:23:00.000,524
2015-12-12,1,1,14,26460000,95,True,10329406735,0,420,21,0,13,20,2015-12-11T23:05:30.000,441
2015-12-11,0,0,12,28920000,95,True,10323887643,0,460,22,0,12,22,2015-12-10T22:27:30.000,482

In [51]:
sleep_logs.to_csv('data/sleep_list.csv')